### PR TITLE
Switch to using latest QRZ dataset.

### PR DESCRIPTION
**Pull request by jsvcycling**
Fixes issue #2.

### CODE REVIEW

**Comment by jsvcycling** [comment]
And issue #1 while we're at it.

**Comment by gravypod** [comment]
Would you mind changing this to use tabs? Your additions are using spaces and I'm not sure if the python VM will play nice with that. 

After you do that I'll mainline that.

**Comment by jsvcycling** [comment]
Yeah sure, I'll do it in a bit.

**Comment by jsvcycling** [comment]
That should do it.

**Pull request merged**
